if __name__ == '__main__':
    app.run_server(debug=True, port=8054)

    # Specify the URL you want to open
    url = "http://127.0.0.1:8054/"
    
    # Open the URL in the default web browser
    webbrowser.open(url)
    
I would like to do webbrowser.open(url) if the url is not already open





Great the result appear below

tabs-1
tabs-2
├── tabs-2 (value)
│   ├── stored-df1 (data)
│   │   ├── fig-dropdown-genres-tab-2 (options)
│   │   └── graph-output-tab-2 (figure)
│   ├── y-dropdown-tab-2 (options)
│   ├── z-dropdown-tab-2 (options)
│   ├── Func-dropdown-tab-2 (options)
│   ├── Dim-dropdown-tab-2 (options)
│   ├── Graph-dropdown-tab-2 (options)
│   ├── Graph-dropdown-tab-2 (value)
│   │   └── graph-output-tab-2 (figure)
│   ├── fig-dropdown-genres-tab-2 (options)
│   └── graph-output-tab-2 (figure)
├── x-dropdown-tab-2 (value)
│   ├── stored-df1 (data)
│   │   ├── fig-dropdown-genres-tab-2 (options)
│   │   └── graph-output-tab-2 (figure)
│   ├── y-dropdown-tab-2 (options)
│   ├── z-dropdown-tab-2 (options)
│   └── graph-output-tab-2 (figure)
├── y-dropdown-tab-2 (value)
│   ├── stored-df1 (data)
│   │   ├── fig-dropdown-genres-tab-2 (options)
│   │   └── graph-output-tab-2 (figure)
│   ├── z-dropdown-tab-2 (options)
│   ├── Func-dropdown-tab-2 (options)
│   ├── Dim-dropdown-tab-2 (options)
│   └── graph-output-tab-2 (figure)
├── z-dropdown-tab-2 (value)
│   ├── stored-df1 (data)
│   │   ├── fig-dropdown-genres-tab-2 (options)
│   │   └── graph-output-tab-2 (figure)
│   └── graph-output-tab-2 (figure)
├── checkbox-startYear-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── checkbox-runtimeMinutes-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── checkbox-genres-tab-2 (value)
│   ├── stored-df1 (data)
│   │   ├── fig-dropdown-genres-tab-2 (options)
│   │   └── graph-output-tab-2 (figure)
│   └── fig-dropdown-genres-tab-2 (options)
├── checkbox-isAdult-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── checkbox-averageRating-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── checkbox-numVotes-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-startYear-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-runtimeMinutes-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-genres-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-isAdult-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-averageRating-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-numVotes-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── Dim-dropdown-tab-2 (value)
│   ├── Graph-dropdown-tab-2 (options)
│   ├── Graph-dropdown-tab-2 (value)
│   │   └── graph-output-tab-2 (figure)
│   └── graph-output-tab-2 (figure)
├── stored-df1 (data)
│   ├── fig-dropdown-genres-tab-2 (options)
│   └── graph-output-tab-2 (figure)
├── Func-dropdown-tab-2 (value)
│   └── graph-output-tab-2 (figure)
├── Graph-dropdown-tab-2 (value)
│   └── graph-output-tab-2 (figure)
tabs-3


Now I want you to look for the dropdonw which look the same and are doing exavtly the same chain.
For instance all the fig-dropdown-"something"-tab-2 (value) are doing 
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)

so I want you insteated of doing 

├── fig-dropdown-startYear-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-runtimeMinutes-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-genres-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-isAdult-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-averageRating-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)
├── fig-dropdown-numVotes-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)

to print it like 

├── List of fig-dropdown-*-tab-2 (value)
│   └── stored-df1 (data)
│       ├── fig-dropdown-genres-tab-2 (options)
│       └── graph-output-tab-2 (figure)